print("What is your mother's age? ")
a=int(input())
print("What is your father's age?")
b=int(input())
print("What is your age?")
c=int(input())
print("What is the current year?")
current_year=int(input())
mothers_birthyear=(current_year-a)
fathers_birthyear=(current_year-b)
your_birthyear=(current_year-c)
print("Father's year of birth is ")
print(fathers_birthyear)
print("Mother's year of birth is ")
print(mothers_birthyear)
print("Your birth year of birth is")
print(your_birthyear)
